name: 'Run semgrep with reviewdog'
description: '🐶 Run semgrep with reviewdog on pull requests to improve code review experience.'
author: 'mgrachev (reviewdog)'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    required: true
  tool_name:
    description: 'Tool name to use for reviewdog reporter'
    default: 'semgrep'
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'warning'
  reporter:
    description: |
      Reporter of reviewdog command [github-pr-check,github-pr-review].
      Default is github-pr-check.
    default: 'github-pr-check'
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    default: 'added'
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    default: 'false'
  reviewdog_flags:
    description: 'Additional reviewdog flags'
    default: ''
  semgrep_flags:
    description: 'Semgrep flags'
    default: '--disable-version-check --verbose --config=p/ci'
  semgrep_ignore:
    description: 'Custom semgrep ignore fingerprint file'
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.tool_name }}
    - ${{ inputs.level }}
    - ${{ inputs.reporter }}
    - ${{ inputs.filter_mode }}
    - ${{ inputs.fail_on_error }}
    - ${{ inputs.reviewdog_flags }}
    - ${{ inputs.semgrep_flags }}
    - ${{ inputs.semgrep_ignore }}
branding:
  icon: 'check-circle'
  color: 'red'
